//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 04/10/2022 22:38:09
namespace csj
{
    
    /// <summary>
    /// There are no comments for csjJoinCarnetsEntities in the schema.
    /// </summary>
    public partial class csjJoinCarnetsEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new csjJoinCarnetsEntities object using the connection string found in the 'csjJoinCarnetsEntities' section of the application configuration file.
        /// </summary>
        public csjJoinCarnetsEntities() : 
                base("name=csjJoinCarnetsEntities", "csjJoinCarnetsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new csjJoinCarnetsEntities object.
        /// </summary>
        public csjJoinCarnetsEntities(string connectionString) : 
                base(connectionString, "csjJoinCarnetsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new csjJoinCarnetsEntities object.
        /// </summary>
        public csjJoinCarnetsEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "csjJoinCarnetsEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for ListaCarnets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ListaCarnets> ListaCarnets
        {
            get
            {
                if ((this._ListaCarnets == null))
                {
                    this._ListaCarnets = base.CreateQuery<ListaCarnets>("[ListaCarnets]");
                }
                return this._ListaCarnets;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ListaCarnets> _ListaCarnets;
        /// <summary>
        /// There are no comments for ListaCarnets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToListaCarnets(ListaCarnets listaCarnets)
        {
            base.AddObject("ListaCarnets", listaCarnets);
        }
    }
    /// <summary>
    /// There are no comments for csjModelCarnetView.ListaCarnets in the schema.
    /// </summary>
    /// <KeyProperties>
    /// carnet_qr
    /// nombres
    /// apellidos
    /// descripcion
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="csjModelCarnetView", Name="ListaCarnets")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ListaCarnets : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ListaCarnets object.
        /// </summary>
        /// <param name="carnet_qr">Initial value of carnet_qr.</param>
        /// <param name="nombres">Initial value of nombres.</param>
        /// <param name="apellidos">Initial value of apellidos.</param>
        /// <param name="descripcion">Initial value of descripcion.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ListaCarnets CreateListaCarnets(string carnet_qr, string nombres, string apellidos, string descripcion)
        {
            ListaCarnets listaCarnets = new ListaCarnets();
            listaCarnets.carnet_qr = carnet_qr;
            listaCarnets.nombres = nombres;
            listaCarnets.apellidos = apellidos;
            listaCarnets.descripcion = descripcion;
            return listaCarnets;
        }
        /// <summary>
        /// There are no comments for property carnet_qr in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string carnet_qr
        {
            get
            {
                return this._carnet_qr;
            }
            set
            {
                this.Oncarnet_qrChanging(value);
                this.ReportPropertyChanging("carnet_qr");
                this._carnet_qr = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("carnet_qr");
                this.Oncarnet_qrChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _carnet_qr;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Oncarnet_qrChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Oncarnet_qrChanged();
        /// <summary>
        /// There are no comments for property documento_nro in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string documento_nro
        {
            get
            {
                return this._documento_nro;
            }
            set
            {
                this.Ondocumento_nroChanging(value);
                this.ReportPropertyChanging("documento_nro");
                this._documento_nro = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("documento_nro");
                this.Ondocumento_nroChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _documento_nro;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondocumento_nroChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondocumento_nroChanged();
        /// <summary>
        /// There are no comments for property nombres in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string nombres
        {
            get
            {
                return this._nombres;
            }
            set
            {
                this.OnnombresChanging(value);
                this.ReportPropertyChanging("nombres");
                this._nombres = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("nombres");
                this.OnnombresChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _nombres;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnombresChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnnombresChanged();
        /// <summary>
        /// There are no comments for property apellidos in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string apellidos
        {
            get
            {
                return this._apellidos;
            }
            set
            {
                this.OnapellidosChanging(value);
                this.ReportPropertyChanging("apellidos");
                this._apellidos = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("apellidos");
                this.OnapellidosChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _apellidos;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnapellidosChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnapellidosChanged();
        /// <summary>
        /// There are no comments for property descripcion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string descripcion
        {
            get
            {
                return this._descripcion;
            }
            set
            {
                this.OndescripcionChanging(value);
                this.ReportPropertyChanging("descripcion");
                this._descripcion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("descripcion");
                this.OndescripcionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _descripcion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndescripcionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndescripcionChanged();
        /// <summary>
        /// There are no comments for property fecha_expedicion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> fecha_expedicion
        {
            get
            {
                return this._fecha_expedicion;
            }
            set
            {
                this.Onfecha_expedicionChanging(value);
                this.ReportPropertyChanging("fecha_expedicion");
                this._fecha_expedicion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fecha_expedicion");
                this.Onfecha_expedicionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _fecha_expedicion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onfecha_expedicionChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onfecha_expedicionChanged();
        /// <summary>
        /// There are no comments for property fecha_vencimiento in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> fecha_vencimiento
        {
            get
            {
                return this._fecha_vencimiento;
            }
            set
            {
                this.Onfecha_vencimientoChanging(value);
                this.ReportPropertyChanging("fecha_vencimiento");
                this._fecha_vencimiento = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fecha_vencimiento");
                this.Onfecha_vencimientoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _fecha_vencimiento;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onfecha_vencimientoChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onfecha_vencimientoChanged();
        /// <summary>
        /// There are no comments for property liquidacion_nro in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string liquidacion_nro
        {
            get
            {
                return this._liquidacion_nro;
            }
            set
            {
                this.Onliquidacion_nroChanging(value);
                this.ReportPropertyChanging("liquidacion_nro");
                this._liquidacion_nro = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("liquidacion_nro");
                this.Onliquidacion_nroChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _liquidacion_nro;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onliquidacion_nroChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onliquidacion_nroChanged();
    }
}
