//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 04/10/2022 22:38:10
namespace csj
{
    
    /// <summary>
    /// There are no comments for csjEntityDomicilio in the schema.
    /// </summary>
    public partial class csjEntityDomicilio : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new csjEntityDomicilio object using the connection string found in the 'csjEntityDomicilio' section of the application configuration file.
        /// </summary>
        public csjEntityDomicilio() : 
                base("name=csjEntityDomicilio", "csjEntityDomicilio")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new csjEntityDomicilio object.
        /// </summary>
        public csjEntityDomicilio(string connectionString) : 
                base(connectionString, "csjEntityDomicilio")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new csjEntityDomicilio object.
        /// </summary>
        public csjEntityDomicilio(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "csjEntityDomicilio")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for domicilio in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<domicilio> domicilio
        {
            get
            {
                if ((this._domicilio == null))
                {
                    this._domicilio = base.CreateQuery<domicilio>("[domicilio]");
                }
                return this._domicilio;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<domicilio> _domicilio;
        /// <summary>
        /// There are no comments for domicilio in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTodomicilio(domicilio domicilio)
        {
            base.AddObject("domicilio", domicilio);
        }
    }
    /// <summary>
    /// There are no comments for csjModelDomicilio.domicilio in the schema.
    /// </summary>
    /// <KeyProperties>
    /// domicilio_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="csjModelDomicilio", Name="domicilio")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class domicilio : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new domicilio object.
        /// </summary>
        /// <param name="domicilio_id">Initial value of domicilio_id.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static domicilio Createdomicilio(int domicilio_id)
        {
            domicilio domicilio = new domicilio();
            domicilio.domicilio_id = domicilio_id;
            return domicilio;
        }
        /// <summary>
        /// There are no comments for property domicilio_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int domicilio_id
        {
            get
            {
                return this._domicilio_id;
            }
            set
            {
                this.Ondomicilio_idChanging(value);
                this.ReportPropertyChanging("domicilio_id");
                this._domicilio_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("domicilio_id");
                this.Ondomicilio_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _domicilio_id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondomicilio_idChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondomicilio_idChanged();
        /// <summary>
        /// There are no comments for property persona_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> persona_id
        {
            get
            {
                return this._persona_id;
            }
            set
            {
                this.Onpersona_idChanging(value);
                this.ReportPropertyChanging("persona_id");
                this._persona_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("persona_id");
                this.Onpersona_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _persona_id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onpersona_idChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onpersona_idChanged();
        /// <summary>
        /// There are no comments for property profesional_tipo_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<short> profesional_tipo_id
        {
            get
            {
                return this._profesional_tipo_id;
            }
            set
            {
                this.Onprofesional_tipo_idChanging(value);
                this.ReportPropertyChanging("profesional_tipo_id");
                this._profesional_tipo_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("profesional_tipo_id");
                this.Onprofesional_tipo_idChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<short> _profesional_tipo_id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onprofesional_tipo_idChanging(global::System.Nullable<short> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onprofesional_tipo_idChanged();
        /// <summary>
        /// There are no comments for property domicilio_tipo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string domicilio_tipo
        {
            get
            {
                return this._domicilio_tipo;
            }
            set
            {
                this.Ondomicilio_tipoChanging(value);
                this.ReportPropertyChanging("domicilio_tipo");
                this._domicilio_tipo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("domicilio_tipo");
                this.Ondomicilio_tipoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _domicilio_tipo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondomicilio_tipoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ondomicilio_tipoChanged();
        /// <summary>
        /// There are no comments for property localidad in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string localidad
        {
            get
            {
                return this._localidad;
            }
            set
            {
                this.OnlocalidadChanging(value);
                this.ReportPropertyChanging("localidad");
                this._localidad = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("localidad");
                this.OnlocalidadChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _localidad;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnlocalidadChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnlocalidadChanged();
        /// <summary>
        /// There are no comments for property calle in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string calle
        {
            get
            {
                return this._calle;
            }
            set
            {
                this.OncalleChanging(value);
                this.ReportPropertyChanging("calle");
                this._calle = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("calle");
                this.OncalleChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _calle;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncalleChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OncalleChanged();
        /// <summary>
        /// There are no comments for property telefono1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string telefono1
        {
            get
            {
                return this._telefono1;
            }
            set
            {
                this.Ontelefono1Changing(value);
                this.ReportPropertyChanging("telefono1");
                this._telefono1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("telefono1");
                this.Ontelefono1Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _telefono1;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ontelefono1Changing(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ontelefono1Changed();
        /// <summary>
        /// There are no comments for property telefono2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string telefono2
        {
            get
            {
                return this._telefono2;
            }
            set
            {
                this.Ontelefono2Changing(value);
                this.ReportPropertyChanging("telefono2");
                this._telefono2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("telefono2");
                this.Ontelefono2Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _telefono2;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ontelefono2Changing(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Ontelefono2Changed();
        /// <summary>
        /// There are no comments for property correo_electronico in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string correo_electronico
        {
            get
            {
                return this._correo_electronico;
            }
            set
            {
                this.Oncorreo_electronicoChanging(value);
                this.ReportPropertyChanging("correo_electronico");
                this._correo_electronico = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("correo_electronico");
                this.Oncorreo_electronicoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _correo_electronico;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Oncorreo_electronicoChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Oncorreo_electronicoChanged();
        /// <summary>
        /// There are no comments for property localidad_codigo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> localidad_codigo
        {
            get
            {
                return this._localidad_codigo;
            }
            set
            {
                this.Onlocalidad_codigoChanging(value);
                this.ReportPropertyChanging("localidad_codigo");
                this._localidad_codigo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("localidad_codigo");
                this.Onlocalidad_codigoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _localidad_codigo;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onlocalidad_codigoChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onlocalidad_codigoChanged();
    }
}
