//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8813
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Nombre de archivo original:
// Fecha de generación: 06/09/2022 10:39:05
namespace csj
{
    
    /// <summary>
    /// No hay ningún comentario para csjJoinCarnetsEntities en el esquema.
    /// </summary>
    public partial class csjJoinCarnetsEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inicializa un nuevo objeto csjJoinCarnetsEntities usando la cadena de conexión encontrada en la sección 'csjJoinCarnetsEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public csjJoinCarnetsEntities() : 
                base("name=csjJoinCarnetsEntities", "csjJoinCarnetsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto csjJoinCarnetsEntities.
        /// </summary>
        public csjJoinCarnetsEntities(string connectionString) : 
                base(connectionString, "csjJoinCarnetsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto csjJoinCarnetsEntities.
        /// </summary>
        public csjJoinCarnetsEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "csjJoinCarnetsEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// No hay ningún comentario para ListaCarnets en el esquema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ListaCarnets> ListaCarnets
        {
            get
            {
                if ((this._ListaCarnets == null))
                {
                    this._ListaCarnets = base.CreateQuery<ListaCarnets>("[ListaCarnets]");
                }
                return this._ListaCarnets;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ListaCarnets> _ListaCarnets;
        /// <summary>
        /// No hay ningún comentario para ListaCarnets en el esquema.
        /// </summary>
        public void AddToListaCarnets(ListaCarnets listaCarnets)
        {
            base.AddObject("ListaCarnets", listaCarnets);
        }
    }
    /// <summary>
    /// No hay ningún comentario para csjModelCarnetView.ListaCarnets en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// carnet_qr
    /// nombres
    /// apellidos
    /// descripcion
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="csjModelCarnetView", Name="ListaCarnets")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ListaCarnets : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto ListaCarnets.
        /// </summary>
        /// <param name="carnet_qr">Valor inicial de carnet_qr.</param>
        /// <param name="nombres">Valor inicial de nombres.</param>
        /// <param name="apellidos">Valor inicial de apellidos.</param>
        /// <param name="descripcion">Valor inicial de descripcion.</param>
        public static ListaCarnets CreateListaCarnets(string carnet_qr, string nombres, string apellidos, string descripcion)
        {
            ListaCarnets listaCarnets = new ListaCarnets();
            listaCarnets.carnet_qr = carnet_qr;
            listaCarnets.nombres = nombres;
            listaCarnets.apellidos = apellidos;
            listaCarnets.descripcion = descripcion;
            return listaCarnets;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad carnet_qr en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string carnet_qr
        {
            get
            {
                return this._carnet_qr;
            }
            set
            {
                this.Oncarnet_qrChanging(value);
                this.ReportPropertyChanging("carnet_qr");
                this._carnet_qr = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("carnet_qr");
                this.Oncarnet_qrChanged();
            }
        }
        private string _carnet_qr;
        partial void Oncarnet_qrChanging(string value);
        partial void Oncarnet_qrChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad documento_nro en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string documento_nro
        {
            get
            {
                return this._documento_nro;
            }
            set
            {
                this.Ondocumento_nroChanging(value);
                this.ReportPropertyChanging("documento_nro");
                this._documento_nro = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("documento_nro");
                this.Ondocumento_nroChanged();
            }
        }
        private string _documento_nro;
        partial void Ondocumento_nroChanging(string value);
        partial void Ondocumento_nroChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad nombres en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string nombres
        {
            get
            {
                return this._nombres;
            }
            set
            {
                this.OnnombresChanging(value);
                this.ReportPropertyChanging("nombres");
                this._nombres = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("nombres");
                this.OnnombresChanged();
            }
        }
        private string _nombres;
        partial void OnnombresChanging(string value);
        partial void OnnombresChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad apellidos en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidos
        {
            get
            {
                return this._apellidos;
            }
            set
            {
                this.OnapellidosChanging(value);
                this.ReportPropertyChanging("apellidos");
                this._apellidos = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("apellidos");
                this.OnapellidosChanged();
            }
        }
        private string _apellidos;
        partial void OnapellidosChanging(string value);
        partial void OnapellidosChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad descripcion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this._descripcion;
            }
            set
            {
                this.OndescripcionChanging(value);
                this.ReportPropertyChanging("descripcion");
                this._descripcion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("descripcion");
                this.OndescripcionChanged();
            }
        }
        private string _descripcion;
        partial void OndescripcionChanging(string value);
        partial void OndescripcionChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad fecha_expedicion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> fecha_expedicion
        {
            get
            {
                return this._fecha_expedicion;
            }
            set
            {
                this.Onfecha_expedicionChanging(value);
                this.ReportPropertyChanging("fecha_expedicion");
                this._fecha_expedicion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fecha_expedicion");
                this.Onfecha_expedicionChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _fecha_expedicion;
        partial void Onfecha_expedicionChanging(global::System.Nullable<global::System.DateTime> value);
        partial void Onfecha_expedicionChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad fecha_vencimiento en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> fecha_vencimiento
        {
            get
            {
                return this._fecha_vencimiento;
            }
            set
            {
                this.Onfecha_vencimientoChanging(value);
                this.ReportPropertyChanging("fecha_vencimiento");
                this._fecha_vencimiento = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fecha_vencimiento");
                this.Onfecha_vencimientoChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _fecha_vencimiento;
        partial void Onfecha_vencimientoChanging(global::System.Nullable<global::System.DateTime> value);
        partial void Onfecha_vencimientoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad liquidacion_nro en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string liquidacion_nro
        {
            get
            {
                return this._liquidacion_nro;
            }
            set
            {
                this.Onliquidacion_nroChanging(value);
                this.ReportPropertyChanging("liquidacion_nro");
                this._liquidacion_nro = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("liquidacion_nro");
                this.Onliquidacion_nroChanged();
            }
        }
        private string _liquidacion_nro;
        partial void Onliquidacion_nroChanging(string value);
        partial void Onliquidacion_nroChanged();
    }
}
