//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8813
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Nombre de archivo original:
// Fecha de generación: 06/09/2022 10:24:02
namespace csj
{
    
    /// <summary>
    /// No hay ningún comentario para csjEntityCarnet en el esquema.
    /// </summary>
    public partial class csjEntityCarnet : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inicializa un nuevo objeto csjEntityCarnet usando la cadena de conexión encontrada en la sección 'csjEntityCarnet' del archivo de configuración de la aplicación.
        /// </summary>
        public csjEntityCarnet() : 
                base("name=csjEntityCarnet", "csjEntityCarnet")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto csjEntityCarnet.
        /// </summary>
        public csjEntityCarnet(string connectionString) : 
                base(connectionString, "csjEntityCarnet")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto csjEntityCarnet.
        /// </summary>
        public csjEntityCarnet(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "csjEntityCarnet")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// No hay ningún comentario para carnet en el esquema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<carnet> carnet
        {
            get
            {
                if ((this._carnet == null))
                {
                    this._carnet = base.CreateQuery<carnet>("[carnet]");
                }
                return this._carnet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<carnet> _carnet;
        /// <summary>
        /// No hay ningún comentario para carnet en el esquema.
        /// </summary>
        public void AddTocarnet(carnet carnet)
        {
            base.AddObject("carnet", carnet);
        }
    }
    /// <summary>
    /// No hay ningún comentario para csjCarnetModel.carnet en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// carnet_qr
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="csjCarnetModel", Name="carnet")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class carnet : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto carnet.
        /// </summary>
        /// <param name="carnet_qr">Valor inicial de carnet_qr.</param>
        /// <param name="persona_id">Valor inicial de persona_id.</param>
        /// <param name="profesional_tipo_id">Valor inicial de profesional_tipo_id.</param>
        /// <param name="impreso">Valor inicial de impreso.</param>
        public static carnet Createcarnet(string carnet_qr, int persona_id, short profesional_tipo_id, bool impreso)
        {
            carnet carnet = new carnet();
            carnet.carnet_qr = carnet_qr;
            carnet.persona_id = persona_id;
            carnet.profesional_tipo_id = profesional_tipo_id;
            carnet.impreso = impreso;
            return carnet;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad carnet_qr en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string carnet_qr
        {
            get
            {
                return this._carnet_qr;
            }
            set
            {
                this.Oncarnet_qrChanging(value);
                this.ReportPropertyChanging("carnet_qr");
                this._carnet_qr = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("carnet_qr");
                this.Oncarnet_qrChanged();
            }
        }
        private string _carnet_qr;
        partial void Oncarnet_qrChanging(string value);
        partial void Oncarnet_qrChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad persona_id en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int persona_id
        {
            get
            {
                return this._persona_id;
            }
            set
            {
                this.Onpersona_idChanging(value);
                this.ReportPropertyChanging("persona_id");
                this._persona_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("persona_id");
                this.Onpersona_idChanged();
            }
        }
        private int _persona_id;
        partial void Onpersona_idChanging(int value);
        partial void Onpersona_idChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad profesional_tipo_id en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short profesional_tipo_id
        {
            get
            {
                return this._profesional_tipo_id;
            }
            set
            {
                this.Onprofesional_tipo_idChanging(value);
                this.ReportPropertyChanging("profesional_tipo_id");
                this._profesional_tipo_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("profesional_tipo_id");
                this.Onprofesional_tipo_idChanged();
            }
        }
        private short _profesional_tipo_id;
        partial void Onprofesional_tipo_idChanging(short value);
        partial void Onprofesional_tipo_idChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad impreso en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool impreso
        {
            get
            {
                return this._impreso;
            }
            set
            {
                this.OnimpresoChanging(value);
                this.ReportPropertyChanging("impreso");
                this._impreso = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("impreso");
                this.OnimpresoChanged();
            }
        }
        private bool _impreso;
        partial void OnimpresoChanging(bool value);
        partial void OnimpresoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad turno_id en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> turno_id
        {
            get
            {
                return this._turno_id;
            }
            set
            {
                this.Onturno_idChanging(value);
                this.ReportPropertyChanging("turno_id");
                this._turno_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("turno_id");
                this.Onturno_idChanged();
            }
        }
        private global::System.Nullable<int> _turno_id;
        partial void Onturno_idChanging(global::System.Nullable<int> value);
        partial void Onturno_idChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad fecha_expedicion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> fecha_expedicion
        {
            get
            {
                return this._fecha_expedicion;
            }
            set
            {
                this.Onfecha_expedicionChanging(value);
                this.ReportPropertyChanging("fecha_expedicion");
                this._fecha_expedicion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fecha_expedicion");
                this.Onfecha_expedicionChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _fecha_expedicion;
        partial void Onfecha_expedicionChanging(global::System.Nullable<global::System.DateTime> value);
        partial void Onfecha_expedicionChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad fecha_vencimiento en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> fecha_vencimiento
        {
            get
            {
                return this._fecha_vencimiento;
            }
            set
            {
                this.Onfecha_vencimientoChanging(value);
                this.ReportPropertyChanging("fecha_vencimiento");
                this._fecha_vencimiento = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fecha_vencimiento");
                this.Onfecha_vencimientoChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _fecha_vencimiento;
        partial void Onfecha_vencimientoChanging(global::System.Nullable<global::System.DateTime> value);
        partial void Onfecha_vencimientoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad liquidacion_nro en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string liquidacion_nro
        {
            get
            {
                return this._liquidacion_nro;
            }
            set
            {
                this.Onliquidacion_nroChanging(value);
                this.ReportPropertyChanging("liquidacion_nro");
                this._liquidacion_nro = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("liquidacion_nro");
                this.Onliquidacion_nroChanged();
            }
        }
        private string _liquidacion_nro;
        partial void Onliquidacion_nroChanging(string value);
        partial void Onliquidacion_nroChanged();
    }
}
