//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8813
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Nombre de archivo original:
// Fecha de generación: 15/07/2022 16:01:32
namespace csj
{
    
    /// <summary>
    /// No hay ningún comentario para csjEntityDomicilio en el esquema.
    /// </summary>
    public partial class csjEntityDomicilio : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inicializa un nuevo objeto csjEntityDomicilio usando la cadena de conexión encontrada en la sección 'csjEntityDomicilio' del archivo de configuración de la aplicación.
        /// </summary>
        public csjEntityDomicilio() : 
                base("name=csjEntityDomicilio", "csjEntityDomicilio")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto csjEntityDomicilio.
        /// </summary>
        public csjEntityDomicilio(string connectionString) : 
                base(connectionString, "csjEntityDomicilio")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto csjEntityDomicilio.
        /// </summary>
        public csjEntityDomicilio(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "csjEntityDomicilio")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// No hay ningún comentario para domicilio en el esquema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<domicilio> domicilio
        {
            get
            {
                if ((this._domicilio == null))
                {
                    this._domicilio = base.CreateQuery<domicilio>("[domicilio]");
                }
                return this._domicilio;
            }
        }
        private global::System.Data.Objects.ObjectQuery<domicilio> _domicilio;
        /// <summary>
        /// No hay ningún comentario para domicilio en el esquema.
        /// </summary>
        public void AddTodomicilio(domicilio domicilio)
        {
            base.AddObject("domicilio", domicilio);
        }
    }
    /// <summary>
    /// No hay ningún comentario para csjModelDomicilio.domicilio en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// domicilio_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="csjModelDomicilio", Name="domicilio")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class domicilio : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto domicilio.
        /// </summary>
        /// <param name="domicilio_id">Valor inicial de domicilio_id.</param>
        public static domicilio Createdomicilio(int domicilio_id)
        {
            domicilio domicilio = new domicilio();
            domicilio.domicilio_id = domicilio_id;
            return domicilio;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad domicilio_id en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int domicilio_id
        {
            get
            {
                return this._domicilio_id;
            }
            set
            {
                this.Ondomicilio_idChanging(value);
                this.ReportPropertyChanging("domicilio_id");
                this._domicilio_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("domicilio_id");
                this.Ondomicilio_idChanged();
            }
        }
        private int _domicilio_id;
        partial void Ondomicilio_idChanging(int value);
        partial void Ondomicilio_idChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad persona_id en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> persona_id
        {
            get
            {
                return this._persona_id;
            }
            set
            {
                this.Onpersona_idChanging(value);
                this.ReportPropertyChanging("persona_id");
                this._persona_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("persona_id");
                this.Onpersona_idChanged();
            }
        }
        private global::System.Nullable<int> _persona_id;
        partial void Onpersona_idChanging(global::System.Nullable<int> value);
        partial void Onpersona_idChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad profesional_tipo_id en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> profesional_tipo_id
        {
            get
            {
                return this._profesional_tipo_id;
            }
            set
            {
                this.Onprofesional_tipo_idChanging(value);
                this.ReportPropertyChanging("profesional_tipo_id");
                this._profesional_tipo_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("profesional_tipo_id");
                this.Onprofesional_tipo_idChanged();
            }
        }
        private global::System.Nullable<short> _profesional_tipo_id;
        partial void Onprofesional_tipo_idChanging(global::System.Nullable<short> value);
        partial void Onprofesional_tipo_idChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad domicilio_tipo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string domicilio_tipo
        {
            get
            {
                return this._domicilio_tipo;
            }
            set
            {
                this.Ondomicilio_tipoChanging(value);
                this.ReportPropertyChanging("domicilio_tipo");
                this._domicilio_tipo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("domicilio_tipo");
                this.Ondomicilio_tipoChanged();
            }
        }
        private string _domicilio_tipo;
        partial void Ondomicilio_tipoChanging(string value);
        partial void Ondomicilio_tipoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad localidad en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string localidad
        {
            get
            {
                return this._localidad;
            }
            set
            {
                this.OnlocalidadChanging(value);
                this.ReportPropertyChanging("localidad");
                this._localidad = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("localidad");
                this.OnlocalidadChanged();
            }
        }
        private string _localidad;
        partial void OnlocalidadChanging(string value);
        partial void OnlocalidadChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad calle en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string calle
        {
            get
            {
                return this._calle;
            }
            set
            {
                this.OncalleChanging(value);
                this.ReportPropertyChanging("calle");
                this._calle = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("calle");
                this.OncalleChanged();
            }
        }
        private string _calle;
        partial void OncalleChanging(string value);
        partial void OncalleChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad telefono1 en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono1
        {
            get
            {
                return this._telefono1;
            }
            set
            {
                this.Ontelefono1Changing(value);
                this.ReportPropertyChanging("telefono1");
                this._telefono1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("telefono1");
                this.Ontelefono1Changed();
            }
        }
        private string _telefono1;
        partial void Ontelefono1Changing(string value);
        partial void Ontelefono1Changed();
        /// <summary>
        /// No hay ningún comentario para la propiedad telefono2 en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono2
        {
            get
            {
                return this._telefono2;
            }
            set
            {
                this.Ontelefono2Changing(value);
                this.ReportPropertyChanging("telefono2");
                this._telefono2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("telefono2");
                this.Ontelefono2Changed();
            }
        }
        private string _telefono2;
        partial void Ontelefono2Changing(string value);
        partial void Ontelefono2Changed();
        /// <summary>
        /// No hay ningún comentario para la propiedad correo_electronico en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string correo_electronico
        {
            get
            {
                return this._correo_electronico;
            }
            set
            {
                this.Oncorreo_electronicoChanging(value);
                this.ReportPropertyChanging("correo_electronico");
                this._correo_electronico = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("correo_electronico");
                this.Oncorreo_electronicoChanged();
            }
        }
        private string _correo_electronico;
        partial void Oncorreo_electronicoChanging(string value);
        partial void Oncorreo_electronicoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad localidad_codigo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> localidad_codigo
        {
            get
            {
                return this._localidad_codigo;
            }
            set
            {
                this.Onlocalidad_codigoChanging(value);
                this.ReportPropertyChanging("localidad_codigo");
                this._localidad_codigo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("localidad_codigo");
                this.Onlocalidad_codigoChanged();
            }
        }
        private global::System.Nullable<int> _localidad_codigo;
        partial void Onlocalidad_codigoChanging(global::System.Nullable<int> value);
        partial void Onlocalidad_codigoChanged();
    }
}
