//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8813
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Nombre de archivo original:
// Fecha de generación: 11/07/2022 18:10:51
namespace csj
{
    
    /// <summary>
    /// No hay ningún comentario para csjEntityPersona en el esquema.
    /// </summary>
    public partial class csjEntityPersona : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inicializa un nuevo objeto csjEntityPersona usando la cadena de conexión encontrada en la sección 'csjEntityPersona' del archivo de configuración de la aplicación.
        /// </summary>
        public csjEntityPersona() : 
                base("name=csjEntityPersona", "csjEntityPersona")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto csjEntityPersona.
        /// </summary>
        public csjEntityPersona(string connectionString) : 
                base(connectionString, "csjEntityPersona")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto csjEntityPersona.
        /// </summary>
        public csjEntityPersona(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "csjEntityPersona")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// No hay ningún comentario para persona en el esquema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<persona> persona
        {
            get
            {
                if ((this._persona == null))
                {
                    this._persona = base.CreateQuery<persona>("[persona]");
                }
                return this._persona;
            }
        }
        private global::System.Data.Objects.ObjectQuery<persona> _persona;
        /// <summary>
        /// No hay ningún comentario para persona en el esquema.
        /// </summary>
        public void AddTopersona(persona persona)
        {
            base.AddObject("persona", persona);
        }
    }
    /// <summary>
    /// No hay ningún comentario para csjPersonaModel.persona en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// persona_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="csjPersonaModel", Name="persona")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class persona : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto persona.
        /// </summary>
        /// <param name="persona_id">Valor inicial de persona_id.</param>
        /// <param name="nombres">Valor inicial de nombres.</param>
        /// <param name="apellidos">Valor inicial de apellidos.</param>
        public static persona Createpersona(int persona_id, string nombres, string apellidos)
        {
            persona persona = new persona();
            persona.persona_id = persona_id;
            persona.nombres = nombres;
            persona.apellidos = apellidos;
            return persona;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad persona_id en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int persona_id
        {
            get
            {
                return this._persona_id;
            }
            set
            {
                this.Onpersona_idChanging(value);
                this.ReportPropertyChanging("persona_id");
                this._persona_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("persona_id");
                this.Onpersona_idChanged();
            }
        }
        private int _persona_id;
        partial void Onpersona_idChanging(int value);
        partial void Onpersona_idChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad documento_tipo_id en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> documento_tipo_id
        {
            get
            {
                return this._documento_tipo_id;
            }
            set
            {
                this.Ondocumento_tipo_idChanging(value);
                this.ReportPropertyChanging("documento_tipo_id");
                this._documento_tipo_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("documento_tipo_id");
                this.Ondocumento_tipo_idChanged();
            }
        }
        private global::System.Nullable<short> _documento_tipo_id;
        partial void Ondocumento_tipo_idChanging(global::System.Nullable<short> value);
        partial void Ondocumento_tipo_idChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad documento_nro en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string documento_nro
        {
            get
            {
                return this._documento_nro;
            }
            set
            {
                this.Ondocumento_nroChanging(value);
                this.ReportPropertyChanging("documento_nro");
                this._documento_nro = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("documento_nro");
                this.Ondocumento_nroChanged();
            }
        }
        private string _documento_nro;
        partial void Ondocumento_nroChanging(string value);
        partial void Ondocumento_nroChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad nombres en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string nombres
        {
            get
            {
                return this._nombres;
            }
            set
            {
                this.OnnombresChanging(value);
                this.ReportPropertyChanging("nombres");
                this._nombres = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("nombres");
                this.OnnombresChanged();
            }
        }
        private string _nombres;
        partial void OnnombresChanging(string value);
        partial void OnnombresChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad apellidos en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidos
        {
            get
            {
                return this._apellidos;
            }
            set
            {
                this.OnapellidosChanging(value);
                this.ReportPropertyChanging("apellidos");
                this._apellidos = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("apellidos");
                this.OnapellidosChanged();
            }
        }
        private string _apellidos;
        partial void OnapellidosChanging(string value);
        partial void OnapellidosChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad sexo en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo
        {
            get
            {
                return this._sexo;
            }
            set
            {
                this.OnsexoChanging(value);
                this.ReportPropertyChanging("sexo");
                this._sexo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("sexo");
                this.OnsexoChanged();
            }
        }
        private string _sexo;
        partial void OnsexoChanging(string value);
        partial void OnsexoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad nacimiento en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> nacimiento
        {
            get
            {
                return this._nacimiento;
            }
            set
            {
                this.OnnacimientoChanging(value);
                this.ReportPropertyChanging("nacimiento");
                this._nacimiento = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("nacimiento");
                this.OnnacimientoChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _nacimiento;
        partial void OnnacimientoChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnnacimientoChanged();
    }
}
