//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8813
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Nombre de archivo original:
// Fecha de generación: 11/07/2022 18:59:11
namespace csj
{
    
    /// <summary>
    /// No hay ningún comentario para csjEntityProfesionalTipo en el esquema.
    /// </summary>
    public partial class csjEntityProfesionalTipo : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inicializa un nuevo objeto csjEntityProfesionalTipo usando la cadena de conexión encontrada en la sección 'csjEntityProfesionalTipo' del archivo de configuración de la aplicación.
        /// </summary>
        public csjEntityProfesionalTipo() : 
                base("name=csjEntityProfesionalTipo", "csjEntityProfesionalTipo")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto csjEntityProfesionalTipo.
        /// </summary>
        public csjEntityProfesionalTipo(string connectionString) : 
                base(connectionString, "csjEntityProfesionalTipo")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto csjEntityProfesionalTipo.
        /// </summary>
        public csjEntityProfesionalTipo(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "csjEntityProfesionalTipo")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// No hay ningún comentario para profesional_tipo en el esquema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<profesional_tipo> profesional_tipo
        {
            get
            {
                if ((this._profesional_tipo == null))
                {
                    this._profesional_tipo = base.CreateQuery<profesional_tipo>("[profesional_tipo]");
                }
                return this._profesional_tipo;
            }
        }
        private global::System.Data.Objects.ObjectQuery<profesional_tipo> _profesional_tipo;
        /// <summary>
        /// No hay ningún comentario para profesional_tipo en el esquema.
        /// </summary>
        public void AddToprofesional_tipo(profesional_tipo profesional_tipo)
        {
            base.AddObject("profesional_tipo", profesional_tipo);
        }
    }
    /// <summary>
    /// No hay ningún comentario para csjProfesionalTipoModel.profesional_tipo en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="csjProfesionalTipoModel", Name="profesional_tipo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class profesional_tipo : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto profesional_tipo.
        /// </summary>
        /// <param name="id">Valor inicial de id.</param>
        /// <param name="descripcion">Valor inicial de descripcion.</param>
        /// <param name="visible">Valor inicial de visible.</param>
        public static profesional_tipo Createprofesional_tipo(short id, string descripcion, bool visible)
        {
            profesional_tipo profesional_tipo = new profesional_tipo();
            profesional_tipo.id = id;
            profesional_tipo.descripcion = descripcion;
            profesional_tipo.visible = visible;
            return profesional_tipo;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad id en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private short _id;
        partial void OnidChanging(short value);
        partial void OnidChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad descripcion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this._descripcion;
            }
            set
            {
                this.OndescripcionChanging(value);
                this.ReportPropertyChanging("descripcion");
                this._descripcion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("descripcion");
                this.OndescripcionChanged();
            }
        }
        private string _descripcion;
        partial void OndescripcionChanging(string value);
        partial void OndescripcionChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad visible en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool visible
        {
            get
            {
                return this._visible;
            }
            set
            {
                this.OnvisibleChanging(value);
                this.ReportPropertyChanging("visible");
                this._visible = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("visible");
                this.OnvisibleChanged();
            }
        }
        private bool _visible;
        partial void OnvisibleChanging(bool value);
        partial void OnvisibleChanged();
    }
}
